src/App.js
src/apis/Api.js
src/apis/SpaceAPICalls.js
src/apis/UserAPICalls.js
src/components/commons/Header.js
src/components/forms/CreateSpaceForm.js
src/modules/SpaceModule.js
src/modules/index.js
src/pages/CreateSpaceSuccessPage.js

공간 등록이 되긴합니다만,
공간 등록이 성공하면 성공페이지로 이동
페이지를 접근할때 토큰인증을과연 잘하고 있는지 등등
수정할 부분이 많아 브랜치삭제는 하지 않겠습니다.

Feature/공간 등록 기능

---

public/index.html
src/components/forms/CreateSpaceForm.js

다음 주소입력 api 사용하도록 구현.
서울 공간일때만 등록할 수 있도록 함.

공간 등록시 주소 입력 api 사용 구현

---

src/App.js
src/apis/ReviewDetailAPICall.js
src/components/forms/ReviewDetailForm.js
src/components/forms/ReviewForm.js
src/modules/ReviewDetailModule.js
src/modules/index.js
src/pages/ReviewDetail.js

리뷰 게시글 상세 페이지

---

src/css/Layout.module.css

body의 min-width를 100%로 변경하여 해결

불필요한 세로 스크롤바 강제 생성 문제  해결

---

src/apis/SpaceAPICalls.js
src/components/forms/CreateSpaceForm.js
src/css/CreateSpaceForm.module.css

공간 등록시 로컬스토리지가 아닌 세션스토리지에서 토큰 가져오기
주석 내용 수정
공간 입력 폼에 간단한 css 추가

[HOTFIX] 급하게 오류 수정

---

src/components/forms/SignupForm.js

[HOTFIX] 회원가입 성공후 로그인페이지로 이동 버튼 url 수정

---

src/components/forms/SignupForm.js
src/components/forms/SignupFormUI.js
src/components/forms/TermsPopup.js
src/css/SignupFormUI.module.css
src/css/TermsPopup.module.css

[HOTFIX] form 수정중

---

src/apis/SpaceAPICalls.js
src/components/forms/CreateSpaceForm.js

공간등록 사진첨부 가능 - 수정필요

---

src/components/forms/EmailDomainSelector.js
src/components/forms/EmailVerification.js
src/components/forms/SignupForm.js
src/components/forms/SignupFormUI.js
src/css/EmailDomainSelector.module.css
src/css/SignupForm.module.css

- EmailDomainSelector 수정
- EmailDomainSelector
- 이메일을 입력받고 인증코드를 인증
- EmailVerifcation 요청문제 수정

[STYLE] css 간단한 수정

---

src/apis/SpaceAPICalls.js
src/components/forms/CreateSpaceForm.js

사진 첨부기능 수정

---

src/apis/ReviewCreateAPICall.js
src/components/forms/CreateReviewForm.js

- CreateReviewForm 수정
- REviewCreateAPICall 수정

리뷰 게시글 이미지 업로드 수정

---

src/components/forms/ReviewDetailForm.js

- ReviewDetailForm return에 img 태그 추가

리뷰 게시글 상세페이지에 이미지 추가

---

src/App.js
src/apis/UserAPICalls.js
src/components/commons/Header.js
src/components/forms/EmailDomainSelector.js
src/components/forms/LoginForm.js
src/css/Header.module.css

헤더 멤버 메뉴 로그인 여부에 따라 변경되게 기능 추가

---

src/components/forms/SignupForm.js
src/components/forms/SignupFormUI.js
src/components/forms/TermsPopup.js
src/css/Signup.module.css
src/css/SignupForm.module.css
src/css/TermsPopup.module.css

- 주소 팝업 무한 호출 문제

---

src/App.js
src/components/commons/CommunitySidebar.js
src/components/commons/Header.js
src/components/forms/MypageForm.js
src/components/forms/ReviewDetailForm.js
src/components/forms/ReviewForm.js
src/css/CommunitySidebar.module.css
src/css/Layout.module.css
src/css/Review.module.css
src/css/Spcaes.module.css
src/pages/Review.js
src/pages/Spaces.js

커뮤니티 사이드바 제작

---

src/components/commons/CommunitySidebar.js
src/css/CommunitySidebar.module.css
src/css/Layout.module.css

사이드바 크기 조정

---

src/App.js
src/apis/MypageAPICall.js
src/components/forms/AddressPopup.js
src/components/forms/EmailDomainSelector.js
src/components/forms/MypageForm.js
src/components/forms/SignupForm.js
src/components/forms/SignupFormUI.js
src/modules/UserModule.js

- 마이페이지 에서 다른 페이지로 이동시 로그아웃 되는거 수정

[FIX] MYPage

---

src/components/forms/MypageForm.js

[HOTFIX] MYPage

---

src/apis/MypageAPICall.js
src/apis/UserAPICalls.js
src/components/forms/MypageForm.js
src/components/forms/SignupForm.js

- 회원정보 수정 기능 ( 정상작동 하도록 변경 ) 
- 현재 비밀번호를 입력해야 정보 수정
- 정상적으로 회원정보가 수정 확인
- 닉네임 과 주소는 기본입력값 표시

[FIX] MYPage 정보 기능 수정

---

src/components/forms/MypageForm.js

- password 입력칸 누락 부분 추가
- newpassword / password

[hotfix] 누락부분 수정

---

src/apis/Api.js
src/apis/EmailVerificationAPICall.js
src/apis/SignupFormAPICall.js
src/components/forms/EmailDomainSelector.js
src/components/forms/EmailVerification.js
src/components/forms/SignupForm.js
src/css/EmailDomainSelector.module.css

[FEATURE]
signup / mypage 함수 관리 js 생성
- signupform
- signupformUI
- mypage
- EmailVerification
이메일 인증 성공시 수정을 불가능 기능
정상 작동 확인
- commit

[FEATURE] Signup 관련 함수 관리 api 

---

src/apis/CommentAPICall.js
src/components/forms/CreateReviewCommentForm.js
src/components/forms/ReviewCommentForm.js
src/components/forms/ReviewDetailForm.js
src/modules/ReviewCommentCreateModule.js
src/modules/ReviewCommentModule.js
src/modules/index.js
src/pages/ReviewDetail.js

리뷰 게시글에 댓글 추가 기능

---

src/App.js
src/apis/InquiryAPICall.js
src/components/commons/CommunitySidebar.js
src/components/forms/InquiryForm.js
src/modules/InquiryModule.js
src/modules/index.js
src/pages/Inquiry.js

- sidebar에 문의 게시판 url 추가
- inquiry, inquiryForm, inquiryAPI, inquiryModule 추가

문의 게시글 전체조회 기능 추가

---

src/App.js
src/apis/InquiryAPICall.js
src/components/forms/CreateInquiryForm.js
src/modules/InquiryCreateModule.js
src/modules/index.js
src/pages/CreateInquiry.js

- inquiryAPICall 에 callCreateInquiryAPI 추가
- inquiryCreatModule 추가
- createInquiry 추가

문의 게시글 추가 기능

---

src/App.js
src/apis/InquiryAPICall.js
src/components/commons/MyPageSidebar.js
src/components/forms/InquiryDetailForm.js
src/components/forms/InquiryForm.js
src/modules/InquiryDetailModule.js
src/modules/index.js
src/pages/InquiryDetail.js

- inquiryDetailForm 추가
- inquiryDetail 추가
- inquiryDetailModule추가
- app에 inquiryDetail추가
- inquiryForm에 잘못된 url 수정
- mypageSidebar에 문의 게시글  url 추가

문의 게시글 상세페이지

---

src/App.js
src/apis/InquiryAPICall.js
src/components/forms/InquiryDetailForm.js
src/components/forms/InquiryUpdateForm.js
src/pages/UpdateInquiry.js

- inquiryUpdateForm 추가
- updateInquiry 추가
- app에 url 추가
- inquiryApiCall 에 수정 부분 추가

문의 게시글 수정기능

---

src/App.js
src/apis/ReportAPICall.js
src/components/commons/CommunitySidebar.js
src/components/forms/ReportForm.js
src/modules/ReportModule.js
src/modules/index.js
src/pages/Report.js

- app에 신고게시글 전체조회url 추가
- reportAPICall 추가
- reportForm 추가
- reportModule 추가
- page에 report 추가
- communitySidebar에 신고게시판 추가

신고 게시글 전체조회

---

src/App.js
src/apis/ReportAPICall.js
src/components/forms/ReportDetailForm.js
src/components/forms/ReportForm.js
src/modules/ReportDetailModule.js
src/modules/index.js
src/pages/ReportDetail.js

- reportForm에 주석 추가, 상세페이지로 이동하는 핸들러에 url 수정
- reportAPICall에 detail추가
- app에 url 추가
- reportDetailModule추가
- reportDetail 추가
- reportDetailForm 추가

게시글 상세페이지 추가

---

src/App.js
src/apis/ReportAPICall.js
src/apis/ReviewAPICall.js
src/components/forms/ReportDetailForm.js
src/components/forms/ReportUpdateForm.js
src/components/forms/ReviewDetailForm.js
src/components/forms/ReviewForm.js
src/pages/UpdateReport.js

- reportAPI, reviewAPI create부분에 게시글 추가후 목록에 바로 적용되게 수정
- reviewUpdateForm 이름 변경
- reportDetailForm 오타 수정
- app url추가, url 변경
- reviewForm url 변경
- reportUpdateForm 추가
- reportAPICall 수정부분 코드 추가
- UpdateReport 추가

신고 게시글 수정페이지 추가

---

src/apis/CommentAPICall.js
src/components/forms/CreateReportCommentForm.js
src/components/forms/ReportCommentForm.js
src/modules/ReportCommentCreateModule.js
src/modules/ReportCommentModule.js
src/modules/index.js
src/pages/ReportDetail.js

- CommentAPICall에 report부분 추가
- reportCommentForm 추가
- CreateReportCommentForm 추가
- ReportCommentCreateModuel 추가
-  reportCommentModule 추가
- reportDetail에 댓글부분 추가
- index에 댓글 모듈 추가

신고 게시글 상세페이지에 댓글 조회 대스글 추가 기능 추가

---

src/apis/Api.js
src/components/forms/InquiryDetailForm.js
src/components/forms/InquiryForm.js
src/components/forms/ReportDetailForm.js
src/components/forms/ReportForm.js
src/components/forms/ReviewDetailForm.js
src/components/forms/ReviewForm.js
src/components/forms/ReviewUpdateForm.js

- 각 게시판에서 수정 후 날짜 안나오는거 수정 (백엔드)
- 각 게시판 form과 detailForm 에 날짜 형식에 맞게 수정
- api tokenRequest에 content type 써서 오류난거 수정( content type 쓰지 마세요)

게시글 수정하면 날짜 안나오는거 수정

---

src/App.js
src/apis/AdministratorAPICall.js
src/apis/Api.js
src/apis/InquiryAPICall.js
src/components/forms/AdministratorForm.js
src/components/forms/MypageForm.js
src/css/AdministratorForm.module.css
src/pages/Administrator.js

- AdministratorAPICall  백엔드 요청
- AdministratorForm 관리자 페이지
- MyPage Get 요청으로 사용자 정보
를 갖고옴 이제 수정 후 업데이트 반영
- commit

[Feature] 관리자 페이지

---

src/App.js
src/components/forms/CreateReviewForm.js
src/components/forms/MyReservationsForm.js
src/components/forms/ReviewForm.js

- createReviewForm에서 reservationId를 받을수 있게 수정
- myReservationForm에서 해당 예약에 이미 리뷰가 있으면 글쓰기가 안보이고 없으면 보이게 설정

리뷰 게시글에 있는 글쓰기 버튼 마이페이지 내예약으로 버튼 옮기기

---

src/apis/InquiryAPICall.js
src/apis/ReviewAPICall.js
src/components/forms/InquiryDetailForm.js
src/components/forms/ReviewDetailForm.js
src/modules/InquiryDeleteModule.js
src/modules/ReviewDeleteModule.js

- inquiryAPI, reviewAPI 에 삭제 api 추가
- inquiry, review detailform에 삭제 버튼과 삭제 핸들러 추가
- inquiry, review deletemodule 추가

게시글 삭제 기능 추가

---

src/components/forms/InquiryDetailForm.js
src/components/forms/ReportDetailForm.js
src/components/forms/ReviewDetailForm.js

- 각각 게시글에 글쓴이와 현재 로그인한 사람을 비교하여 일치하면 수정,삭제 버튼이 보이고 일치하지 않으면 안보이게 수정

게시글 수정삭제 글쓴이만 할 수 있게 수정

---

src/apis/MypageAPICall.js
src/components/commons/MyPageSidebar.js
src/components/forms/MypageForm.js
src/css/MyPage.module.css
src/css/MyPageForm.module.css
src/css/MypageSidebar.module.css
src/pages/Mypage.js

- signup login mypage css 조정
- login
- mypage
- find-email / find-password
- successscreen

[Style] signup login mypage css

---

src/components/forms/EmailVerification.js
src/components/forms/FindEmailForm.js
src/components/forms/MypageForm.js
src/components/forms/SignupFormUI.js
src/css/EmailVerification.module.css
src/css/FindEmailForm.module.css
src/css/MyPage.module.css
src/css/MyPageForm.module.css

- css 조정
- EmailVerification
- MyPage
- FindEmail
- commit

[STYLE] CSS 조정 
